name = "FastSweeping"
uuid = "a6aab1ba-8f88-4217-b671-4d0788596809"
authors = ["François Févotte <francois.fevotte@triscale-innov.com"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
julia = "1.5"
